"""empty message

Revision ID: 3c7a3dd6f884
Revises: 5c7d64eed88c
Create Date: 2021-08-19 00:49:16.031791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c7a3dd6f884'
down_revision = '5c7d64eed88c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('articles_board_id_fkey', 'articles', type_='foreignkey')
    op.drop_constraint('articles_user_id_fkey', 'articles', type_='foreignkey')
    op.create_foreign_key(None, 'articles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'articles', 'boards', ['board_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.create_foreign_key('articles_user_id_fkey', 'articles', 'users', ['user_id'], ['id'])
    op.create_foreign_key('articles_board_id_fkey', 'articles', 'boards', ['board_id'], ['id'])
    # ### end Alembic commands ###
