"""empty message

Revision ID: 5c7d64eed88c
Revises: 9bacae28c0a2
Create Date: 2021-08-19 00:44:06.200319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c7d64eed88c'
down_revision = '9bacae28c0a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('title', sa.String(length=100), nullable=True))
    op.add_column('boards', sa.Column('name', sa.String(length=100), nullable=True))
    op.drop_column('boards', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('boards', 'name')
    op.drop_column('articles', 'title')
    # ### end Alembic commands ###
